import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import { Auxiliary } from './components/modules/auxiliary'
import { Footer } from './components/modules/footer'
import { Header } from './components/modules/header'
import { UserState } from './contexts/user'
import './globals.css'

const inter = Raleway({ subsets: ['cyrillic', 'latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const HEADER_HEIGHT = 70

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-dark`}>
        <UserState>
          <Header />
          <Auxiliary />
          <main className={`min-h-[calc(100vh-70px)]`}>{children}</main>
          <Footer />
        </UserState>
      </body>
    </html>
  )
}
