import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AdminSidebar } from './components/sidebar'
import AdminHashGuard from './guards/hash-guard'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AdminHashGuard>
      <div className='flex gap-4'>
        <AdminSidebar />
        {children}
      </div>
    </AdminHashGuard>
  )
}
